project:
  type: website
  output-dir: docs

website:
  title: "Anjali Suva"
  image: media/SZ0-04.jpg
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Viz"
        menu: 
        - text: "Pixar Films"
          href: pixarfilms.html
        - text: "CBP Encounters"
          href: cbpencounters.html
        - text: "NYTimes Headlines"
          href: nytheadlines.html
        - text: "Company Reputation Sim Study"
          href: companyreputationscores.html
        - text: "Child Welfare Ethical Dilemma"
          href: childwelfareethicaldilemma.html
        - text: "SQL Traffic Stop Data Exploration"
          href: trafficstops.html
        - text: "SQL Traffic Stop Data Presentation"
          href: sqlpresentation.html
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

